---

- name: reload systemd
  command: systemctl --system daemon-reload
  notify: restart daemons

- name: restart kubelet
  service:
    name: kubelet
    state: restarted

- name: restart proxy
  service:
    name: kube-proxy
    state: restarted
