---

- name: Write the config files for proxy
  template:
    src: proxy.j2
    dest: "{{ kube_config_dir }}/proxy"
  notify: restart proxy

- name: Slurp kube CA certificate
  slurp:
    src: "{{ kube_cert_dir }}/ca.crt"
  register: kube_ca_slurp
  run_once: true
  delegate_to: "{{ groups[k8s_hostgroup][0] }}"

- name: Write the kubecfg (auth) file for kube-proxy
  template:
    src: proxy.kubeconfig.j2
    dest: "{{ kube_config_dir }}/proxy.kubeconfig"
  notify: restart proxy
