---

- name: Install packages
  yum:
    name: "flannel-{{ flannel_version }}"
    state: present
    update_cache: true

- name: Install Flannel config file
  template:
    src: flanneld.j2
    dest: "/etc/sysconfig/flanneld"
  notify: restart flannel
  when: not container

